[gaim-migrate @ 17340] Put gaim-text and the gnt stuff into a gaim-text RPM so that our main RPM doesn't depend on ncurses.
rpmbuild -ta gaim-2.0.0dev.tar.bz2 doesn't work for me anymore.  Did it used to?
Does it work for other people?  For me it prints
error: Name field must be present in package: (main package)
error: Version field must be present in package: (main package)
error: Release field must be present in package: (main package)
error: Summary field must be present in package: (main package)
error: Group field must be present in package: (main package)
error: License field must be present in package: (main package)

And it creates a file called "tar: Pattern matching characters used in file n
ames. Please," in my ~/rpmbuild/SPECS directory.  It does not put gaim.spec
in my ~/rpmbuild/SPECS directory, and it does not put anything in
~/rpmbuild/BUILD or ~/rpmbuild/SOURCES, either